In [1]:
setwd("C:/Users/User/Desktop")
aa <- read.csv("wheeze.csv")

In [50]:
X <- cbind(1,factor(aa$city),aa$age,aa$smoke)
y <- aa$wheeze

In [51]:
V=cbind(c(1,0.4117,0.1695,0.0698),c(0.4117,1,0.4117,0.1695),c(0.1695,0.4117,1,0.4117),c(0.0698,0.1695,0.4117,1))
V

[,1]   [,2]   [,3]   [,4]  
[1,] 1.0000 0.4117 0.1695 0.0698
[2,] 0.4117 1.0000 0.4117 0.1695
[3,] 0.1695 0.4117 1.0000 0.4117
[4,] 0.0698 0.1695 0.4117 1.0000

In [52]:
V <- diag(16) %x% V

In [53]:
solve(t(X)%*%solve(V)%*%X)

[,1]        [,2]          [,3]          [,4]        
[1,]  1.69411426 -0.1678903444 -0.1358269095  0.014436462
[2,] -0.16789034  0.1113915105  0.0003364095 -0.003373472
[3,] -0.13582691  0.0003364095  0.0131904677 -0.003927712
[4,]  0.01443646 -0.0033734717 -0.0039277122  0.039386593

In [17]:
X

[,1] [,2] [,3] [,4]
 [1,] 1    2     9   0   
 [2,] 1    2    10   0   
 [3,] 1    2    11   0   
 [4,] 1    2    12   0   
 [5,] 1    1     9   1   
 [6,] 1    1    10   2   
 [7,] 1    1    11   2   
 [8,] 1    1    12   2   
 [9,] 1    1     9   0   
[10,] 1    1    10   0   
[11,] 1    1    11   1   
[12,] 1    1    12   1   
[13,] 1    2     9   0   
[14,] 1    2    10   0   
[15,] 1    2    11   0   
[16,] 1    2    12   1   
[17,] 1    1     9   0   
[18,] 1    1    10   1   
[19,] 1    1    11   1   
[20,] 1    1    12   1   
[21,] 1    2     9   0   
[22,] 1    2    10   1   
[23,] 1    2    11   1   
[24,] 1    2    12   1   
[25,] 1    1     9   1   
[26,] 1    1    10   1   
[27,] 1    1    11   0   
[28,] 1    1    12   0   
[29,] 1    2     9   1   
[30,] 1    2    10   1   
[31,] ...  ...  ...  ... 
[32,] 1    2    11   1   
[33,] 1    2    12   1   
[34,] 1    1     9   0   
[35,] 1    1    10   0   
[36,] 1    1    11   0   
[37,] 1    1    12   1   
[38,] 1    1     9   1   
[39,] 1    1    10   0   
[40,] 1    1    11   0   
[41,] 1    1    12   0   
[42,] 1    2     9   1   
[43,] 1    2    10   0   
[44,] 1    2    11   0   
[45,] 1    2    12   0   
[46,] 1    1     9   1   
[47,] 1    1    10   0   
[48,] 1    1    11   1   
[49,] 1    1    12   1   
[50,] 1    2     9   1   
[51,] 1    2    10   2   
[52,] 1    2    11   1   
[53,] 1    2    12   2   
[54,] 1    1     9   1   
[55,] 1    1    10   1   
[56,] 1    1    11   1   
[57,] 1    1    12   2   
[58,] 1    2     9   1   
[59,] 1    2    10   1   
[60,] 1    2    11   2   
[61,] 1    2    12   1

In [11]:
t(X)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:2: 未預期的 INCOMPLETE_STRING
1: X'
     ^
